#!/bin/bash

. ./00.variables.sh
SESSION_NAME=$(cat ${WORKDIR}/${SESSION_FILENAME})
BEARER_TOKEN=$(cat ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${OAUTH_ACCESS_TOKEN})

TADO_HOME_ID=$(cat ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_DATA_HOME_ID})

echo "invoking uri >${TADO_API_HOME_DETAILS_BASE_URI}/${TADO_HOME_ID}/weather<"
curl -s "${TADO_API_HOME_DETAILS_BASE_URI}/${TADO_HOME_ID}/weather" \
     -H "Authorization: Bearer ${BEARER_TOKEN}" \
     -o ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_API_WEATHER_JSON_RESULT}

#jq .homeId ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_API_PROFILE_JSON_RESULT} > ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_DATA_HOME_ID}