#!/bin/bash

. ./00.variables.sh
SESSION_NAME=$(cat ${WORKDIR}/${SESSION_FILENAME})
BEARER_TOKEN=$(cat ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${OAUTH_ACCESS_TOKEN})

TADO_HOME_ID=$(cat ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_DATA_HOME_ID})

NR_OF_ZONES=$(jq ". | length" ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_API_ZONES_JSON_RESULT})
zone_idx=0

#CSV_HEADER="ZONE_ID;ZONE_NAME;LINK_TS;LINK_STATE"
#CSV_HEADER="${CSV_HEADER};TEMP_TIMESTAMP;TEMP_VALUE;HUMIDITY_TIMESTAMP;HUMIDITY_VALUE;HEATING_POWER_TIMESTAMP;HEATING_POWER_VALUE"
#CSV_HEADER="${CSV_HEADER};OBJECTIVE_TEMP_VALUE;OBJECTIVE_HEATING_VALUE" 
#echo ${CSV_HEADER} > ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_DATA_CSV}

for aZone in $(seq 1 1 ${NR_OF_ZONES})
do
    echo "Processing zone #${aZone}"
    curl "${TADO_API_HOME_DETAILS_BASE_URI}/${TADO_HOME_ID}/zones/${aZone}/schedule/timetables" \
         -H "Authorization: Bearer ${BEARER_TOKEN}" \
         -o ${WORKDIR}/${SESSION_DIR_PREFIX}${SESSION_NAME}/${TADO_API_PERZONE_JSON_RESULT_PREFIX}_${aZone}_${TADO_API_PERZONE_TIMETABLES_JSON_RESULT_POSTFIX}.json

done